# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: mhamilt.github.io
email: matt.hamilton@ed.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Everything is workflow
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mhamilt.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mhamilt

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: bash
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
theme: minima
#plugins:
#  - jekyll-feed

header_pages:
  - about.md
  - archive.md
  - playground.md
  - time.md

# ~/.rvm/gems/ruby-2.4.2/gems/minima-2.5.0
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
